site_name: test-python-3 Docs

nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - API Reference: API.md
  - SecurityModel: SECURITY.md
  - Developer Onboarding: ONBOARDING.md

theme: readthedocs
